version: '3.8'

services:
  web:
    build: .
    container_name: flask_web
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - redis
      - celery_worker

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A app.tasks worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis

volumes:
  redis_data:
    driver: local

networks:
  default:
    driver: bridge
